version: '2'
services:
#mysql service
  mysql:
    build: ./mysql
    ports:
        - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db:/var/lib/mysql
    restart: "unless-stopped"

#nodejs service
  node:
    image: "node:alpine"
    network_mode: "host"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./app/:/home/node/app
    expose:
      - "8080"
    command: "npm start"
    depends_on:
      - mysql
    restart: "unless-stopped"
volumes:
  db: